import './globals.css'
import { Inter } from 'next/font/google';
import {Navigation} from '../components/Navigation'
import {Providers} from '../store/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rick and Morty App 🎮',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossOrigin="anonymous"
            />
            <title>✨</title>
        </head>
        <body className={inter.className}>
            <Providers>
                <Navigation/>
                <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
                <script  src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
                <script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
                    crossOrigin="anonymous"
                />
                {children}
            </Providers>
        </body>
    </html>
  )
}
